# Generated by Django 3.2.4 on 2021-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210627_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='cal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='calcium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='vita',
            field=models.IntegerField(),
        ),
    ]
