# Generated by Django 3.2.4 on 2021-07-01 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_nutrient_randid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='randid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
